---
name: PR Labels

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled

jobs:
  pr-labels:
    name: PR Labels
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Run Labeler
        uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          labels: >
            breaking-change,
            bugfix,
            chore,
            ci,
            dependencies,
            documentation,
            enhancement,
            maintenance,
            new-feature,
            performance,
            refactor
